spring:
  application:
    name: emaster-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:9099
    #路由网关配置
    gateway:
      #设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      #配置路由规则
      routes:
        #采用自定义路由id
        - id: emaster-sys-service
          #采用loadbalanceClient方式请求，以lb://开头，后面的是注册在nacos上的服务名
          uri: lb://emaster-sys-service
          #predicates翻译过来是谓词的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            #Method 方法谓词，这里是匹配GET 和 POST请求
            - Method=GET,POST
        - id: emaster-flowable-service
          #采用loadbalanceClient方式请求，以lb://开头，后面的是注册在nacos上的服务名
          uri: lb://emaster-flowable-service
          #predicates翻译过来是谓词的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            #Method 方法谓词，这里是匹配GET 和 POST请求
            - Method=GET,POST
server:
  port: 6001

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  sentinel:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: debug
