#spring:
#  application:
#    name: emaster-xxl-job-executor
#server:
#  port: 9004
#xxl:
#  job:
#    accessToken: default_token
#    admin:
#      addresses: http://127.0.0.1:18080/xxl-job-admin
#    executor:
#      appname: emaster-xxl-job-executor
#      port: 9999
#      address:
#      ip:
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30